global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "telco_alerts.yml"

scrape_configs:
  - job_name: 'telco-event-generator'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: 
        - 'kafka1:19092'
        - 'kafka2:19093' 
        - 'kafka3:19094'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']